export const emojiList = [
    '🍔',
    '🍟',
    '🍕',
    '🍜',
    '🍣',
    '🍰',
    '☕',
    '🍺',
    '🛒',
    '🛍️',
    '🎁',
    '🏠',
    '🚗',
    '🚌',
    '🛵',
    '📱',
    '💻',
    '📺',
    '🎮',
    '🎬',
    '🎤',
    '🎨',
    '🏀',
    '⚽',
    '💼',
    '💰',
    '🏦',
    '💳',
    '🩺',
    '💊',
    '✈️',
    '🏖️',
    '🐶',
    '🐱',
    '🧹',
    '🛠️',
    '🛏️',
    
]

export const incomeCategoryList = [
    {icon: '💼', category: 'Salary', defaultRemark: '薪水'},
    {icon: '🎁', category: 'Gift', defaultRemark: '禮物'},
    {icon: '💰', category: 'Bonus', defaultRemark: '獎金'},
    {icon: '📈', category: 'Investment', defaultRemark: '投資'},
  ]

  export const expenseCategoryList = [
      {icon: '🍔', category: 'Food', defaultRemark: '食物'},
      {icon: '🚌', category: 'Transport', defaultRemark: '交通'},
      {icon: '🏠', category: 'Housing', defaultRemark: '房租'},
      {icon: '📱', category: 'Utilities', defaultRemark: '電子產品'},
      {icon: '🎮', category: 'Entertainment', defaultRemark: '娛樂'},
    ]